# SPDX-FileCopyrightText: 2021 Genome Research Ltd.
#
# SPDX-License-Identifier: MIT

# Additional deployment details for testing in CI/CD (includes temporary database)
version: '3'
services: 
  tolid-db:
    image: postgres:11
    env_file:
      - ${ENV_FILE}
    ports:
      - 5432:5432
    networks:
      - tolid
    deploy:
      replicas: 1
