# This is used for staging and production deployment in CI/CD
version: '3.9'
services: 
  tolid-api:
    image: $CI_REGISTRY_IMAGE/tolid-api:$CI_COMMIT_SHA
    restart: always
    networks:
      - tolid
    deploy:
      replicas: 1
    env_file:
      - ${ENV_FILE}
    ports: 
      - 5000:8080
  tolid-ui:
    image: $CI_REGISTRY_IMAGE/tolid-ui:$CI_COMMIT_SHA
    restart: always
    networks:
      - tolid
    deploy:
      replicas: 1
    env_file:
      - ${ENV_FILE}
#    entrypoint: /bin/sh -c "envsubst "\\$$STS_API_LOCATION" < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf && cat /etc/nginx/nginx.conf && nginx -g 'daemon off;'"
    ports: 
      - 8000:80
  tolid-dbutils:
    image: $CI_REGISTRY/tol/sts/dbutils:1.0.2
    restart: always
    networks:
      - tolid
    deploy:
      replicas: 1
    env_file:
      - ${ENV_FILE}
networks:
  tolid:
    driver: overlay